### PR TITLE
Implement changes to hash-to-FORS-leaves transform

### PR DESCRIPTION
**Pull request by sfluhrer**
This is the change to the Sphincs+ definition by NIST

### CODE REVIEW

**Comment by bwesterb** [comment]
```
17c04e422125fb85174d4ea8c3a9ecf4a9c89978c4e0377b9ff0fe7d2c19c69c sphincs-haraka-256s-simple
17f36b05d28409166da940a38682772bc433954fe4918858b8f67a9a31f745c3 sphincs-haraka-192f-robust
1be9620ff5d15d8d23e3245e0540365c521898843021656b0bf056d3aeffdd47 sphincs-haraka-192s-simple
26c8f09e2c25e0455357192a6e79da9a2517dd1c77586e14df46ec53b4447110 sphincs-shake-192s-simple
389c21e8b163bfe902480a25d1e46b002a9962f06728bffc36e3984058a32096 sphincs-sha2-128s-robust
3f6132372ba8851342dae65cf56dc42c80cb6170deb671f502af50247cbda33a sphincs-shake-128s-simple
55f9323eddcdb2eab9a395a97646be46c23a486fe6b935f5b737c8c2c9fee1a5 sphincs-shake-256f-simple
5bbecb2b3588f30f9293d0350ab2a38a4ce3400b778323e7fae2dea85ad0f59b sphincs-shake-128f-simple
5e0e377f51c56ea2b3170b007a1a14b3890d7de6d034b4f5205d8b2df61ee37d sphincs-haraka-192s-robust
6107742e4f6d6e8fda1e38dfe3c3f7a31dcc210e74cee1163f03bb724367911d sphincs-sha2-192f-robust
61431f43e0189c613630861d289546264d072b16bd4a7ce8a46f3818c7d9788b sphincs-sha2-192s-simple
66b0e77fc3633b4b8f9b293ea085a199be9fef29ff999bf95078b2a8d1f9c2ef sphincs-shake-256f-robust
6a807c710a3af935e7ebc6345646edeeb80254a43c60f8d3f0c45957b8ca48d5 sphincs-shake-192f-simple
6c7d566e5e68d324d7b517b18da6b46114b3dc4a652b7c44cb9de7763ad2bba5 sphincs-shake-128s-robust
78a1a34f0ea5521fc10dc67e4b0ab6bdbc513c78e402a41cb6c0d13f3dd778e3 sphincs-sha2-256f-simple
7dac35995d687feaab1c7a6b4ab1aab011ee4622aa2cd5bffd344d746e97b516 sphincs-sha2-128f-robust
7ff980874b5e11dd3f4ad6e850da2bd89f6ec10ca99d17fe4da74d2c6d6f9eb2 sphincs-sha2-128s-simple
8ea260a61bf2ccf3475f189a0762406ec355baac2019de5ddc77ce25deaa768c sphincs-sha2-128f-simple
92e30a899f685818d254effcd81e98b621720ca6eb10ee6b2f95f10674057f79 sphincs-sha2-192s-robust
9a420dd96255a2a960487066370e94582fcd2ca5ad0ae235042734bfb9fcad5f sphincs-haraka-128s-simple
9fb47e799b9798e4cceb98812ba127f51b8992d0381fbadbb7615549df576c20 sphincs-shake-128f-robust
a36b0ddb3b787004e5c28d191965ed1d5c1d2fa0853914ef567520be2acc6114 sphincs-haraka-128f-robust
aa24d6edb5e83f50fc39f79ac40c8918b6daa2ab49e08286e0624959d132e572 sphincs-sha2-256s-simple
aeffef695bb18e34eaaeb9ce3271dc56b1c9a97839076f941a7e367815ae677b sphincs-haraka-256f-simple
b19b1b7c0490b3a717da8ddb98518d0c4f9facd61c6a5e72d1bcfb2e747cbe2c sphincs-shake-256s-robust
bb82d1c813a05f25ce4df62725702ff24a59f8ceac8aecd16e991cb0aaee0945 sphincs-shake-192f-robust
c917fe0e124c16a55da0ba9e2f4b031fe3da5ae5bddbdc43877c9dfcb3dffcb9 sphincs-sha2-192f-simple
d00f5003582881b22d3202400043b633cd7ea60254d31be9b88f726db09645d4 sphincs-haraka-128f-simple
d1e3a732a7b64babb6c8a3fb8585572bb0dacd7c4cae94e150a27447e36f5b61 sphincs-sha2-256s-robust
d7b0ac5f694dbfb39a68c5757cd982467f4eec82fd8197edf697387d028c4bcc sphincs-haraka-256f-robust
e983eb352244b73f3e2a65dfa70adbda739f97034219b926cb14ce15db063acd sphincs-sha2-256f-robust
f15c8e7a639e36ff64d4fbb53d93f32ca8b75df68e2c1dfe0b2f6ad28c091bc9 sphincs-haraka-192f-simple
f425de671b7d5c8f2ba0ef2cbf3e372d4390c85c421b2d47ec8ca899b0ace424 sphincs-shake-192s-robust
f5d034424896f5ed7d76de7722079cb3f934667f6f4cde87bddcfca639d6efc0 sphincs-shake-256s-simple
f92e33c3e04e6d5ffdeecdcb6d838b0aee8070aecf78f5e133d7e092e052bdb7 sphincs-haraka-256s-robust
fb1c3d2922c71221a718e490859d6b556f37c08007b889b794f84d33490c392f sphincs-haraka-128s-robust
```

**Comment by bwesterb** [comment]
Also `message_to_indices` is duplicated several times.

**Comment by bwesterb** [comment]
For your convenience https://github.com/sphincs/sphincsplus/pull/51

**Comment by sfluhrer** [comment]
Bas has the correct changes

**Pull request closed without merging**
