### PR TITLE
Eliminate global state

### LINKED ISSUE #19: Thread safety
We should get rid of the global variables so that it's thread safe.

### PR DESCRIPTION
**Pull request by bwesterb**
Closes #19

### CODE REVIEW

**Comment by kste** [comment]
I think it's very good to get rid of this global state here. I would expect this change to have negligible effect on the performance, but we should still measure it before proceeding. WDYT?

**Comment by bwesterb** [comment]
Yes, it's good to check. I'll run benchmarks.

**Comment by sfluhrer** [comment]
Looks good to me

**Review by sfluhrer — APPROVED** [review]

**Comment by bwesterb** [comment]
Sorted by biggest difference between minimum cycle counts on 10 runs the worst differences are the following. There is quite a bit of noise (there were other things running), but there doesn't seem to be a clear difference.

```
sphincs-sha256-128f robust using sha256-avx2 Generating keypair                  
 old: [2245650, 2304198, 4064057, 2714058, 3308502, 2742562, 2064874, 2187795, 2736259]
 new: [2721770, 2752107, 2122860, 2538116, 2708797, 2004361, 2389892, 1945872, 2720016]
                                                                                 
sphincs-shake256-192f simple using shake256-avx2 Generating keypair              
 old: [2928249, 2925897, 2992434, 4039774, 4072254, 2934061, 3073387, 3098772, 2920138]
 new: [3090888, 4697372, 3079354, 3449380, 3275662, 3453108, 3887092, 3654046, 3069736]
                                                                                 
sphincs-haraka-256f robust using haraka-aesni Generating keypair                 
 old: [2558550, 2558510, 2388922, 3333369, 2296693, 2246871, 2888844, 2993608, 3090114]
 new: [3489086, 2484154, 3508320, 2563840, 2417686, 2710400, 2358792, 3917751, 3585731]
                                                                                 
sphincs-haraka-128s simple using ref Verifying                                   
 old: [4819600, 4790154, 4955367, 4843836, 4725010, 4524348, 4925325, 4870743, 4804944]
 new: [4903477, 4913415, 4808080, 4932486, 4902156, 5085657, 4717312, 4716996, 4717993]
                                                                                 
sphincs-sha256-256f simple using sha256-avx2 Generating keypair                  
 old: [3965956, 4435226, 4447114, 5165148, 6504354, 4674481, 4168512, 4240312, 4174918]
 new: [5139491, 4782037, 4791348, 5751569, 6802767, 4131272, 5790819, 6011984, 6247734]
                                                                                 
sphincs-haraka-128f robust using haraka-aesni Generating keypair                 
 old: [577554, 566952, 631428, 505884, 696576, 777719, 1680798, 546747, 631274]  
 new: [553767, 603034, 761993, 534772, 683004, 661394, 930591, 589650, 525201]   
                                                                                 
sphincs-sha256-128s robust using sha256-avx2 Verifying                           
 old: [1528161, 1548300, 1627378, 1554952, 1525549, 1460452, 1482882, 1491382, 1580167]
 new: [1603558, 1541469, 1637172, 1578636, 1511826, 1618653, 1566039, 1520082, 1534267]
                                                                                 
sphincs-sha256-128f robust using ref Verifying                                   
 old: [14058567, 14027185, 14677893, 14646234, 14617975, 14708367, 14113875, 14424975, 14351434]
 new: [13609837, 13541428, 14639715, 14581236, 15060393, 14349153, 14547526, 14143902, 14450422]
                                                                                 
sphincs-haraka-128f simple using haraka-aesni Generating keypair                 
 old: [553642, 462492, 735678, 502890, 439630, 635507, 534586, 448846, 580548]   
 new: [515496, 585682, 425446, 437202, 500318, 436906, 629228, 626337, 472508]   
                                                                                 
sphincs-haraka-128f simple using ref Verifying                                   
 old: [12691194, 12476572, 12518442, 12399178, 12892486, 12186730, 12559500, 12346914, 12625524]
 new: [12706215, 12964911, 11797102, 12155809, 12776364, 12383266, 12601893, 12311296, 12754396]
                                                                                 
sphincs-sha256-192f simple using sha256-avx2 Generating keypair                  
 old: [1486846, 1529607, 1657478, 2230042, 1625146, 1653734, 1530327, 2244046, 1542735]
 new: [1663388, 1766758, 1545474, 2230120, 1611232, 2146292, 1532999, 1703558, 2089130]
                                                                                 
sphincs-haraka-192s simple using haraka-aesni Verifying                          
 old: [465765, 463485, 450298, 444982, 453772, 455170, 467358, 456904, 456315]   
 new: [472705, 463206, 476374, 469849, 478704, 465156, 474319, 458365, 474592]   
                                                                                 
sphincs-shake256-192f simple using ref Verifying                                 
 old: [16375960, 15923980, 16816161, 16537734, 15896089, 16405014, 16549720, 16550205, 16926081]
 new: [16536007, 16365562, 16460971, 16892094, 16509961, 16371757, 17029639, 16830976, 16481577]
                                                                                 
sphincs-sha256-128s simple using ref Verifying                                   
 old: [2489751, 2178303, 2424442, 2474550, 2473791, 2211855, 2325736, 2440411, 2326954]
 new: [2367234, 2432332, 2464852, 2241624, 2384836, 2383729, 2465554, 2318895, 2254111]
                                                                                 
sphincs-sha256-128f simple using sha256-avx2 Verifying                           
 old: [1959118, 1954698, 1947642, 1962987, 1949340, 1910857, 1922613, 1938130, 1915111]
 new: [1919446, 1857028, 2092519, 1919377, 1919749, 1981420, 2137161, 1958514, 1900905]
 ```

**Pull request merged**
