### PR TITLE
Add shake256-a64 implementation

### PR DESCRIPTION
**Pull request by bwesterb**
Uses the optional SHA3 extension on Armv8.2-A.

### CODE REVIEW

**Comment by kste** [comment]
This is great :-). Can we add this implementation also to the CI checks?

**Comment by bwesterb** [comment]
> This is great :-). Can we add this implementation also to the CI checks?

Github Actions doesn't have ARM runners. We could emulate with qemu, but we'd have to check whether that stays within the runtime limits. I propose to create an issue for that once this is merged.

**Comment by kste** [comment]
Sounds good to me. Did you by any chance manually check whether we get the same test vectors?

**Comment by bwesterb** [comment]
> Sounds good to me. Did you by any chance manually check whether we get the same test vectors?

Yes, I did: they all match.

**Pull request merged**
